import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
const root = path.resolve(import.meta.dirname, "..");
const server = path.join(root, ".next/standalone/server.js");
if (!fs.existsSync(server)) throw new Error("Execute npm run build antes de iniciar.");
const child=spawn(process.execPath,[server],{cwd:path.dirname(server),stdio:"inherit",env:{...process.env,NODE_ENV:"production",HOSTNAME:"0.0.0.0"}});
child.on("error",error=>{console.error(error.message);process.exitCode=1;});
child.on("exit",(code)=>{process.exitCode=code??1;});
for(const signal of ["SIGINT","SIGTERM"])process.on(signal,()=>child.kill(signal));
